### ISSUE TITLE
Set image 1-3 directly without saving to local disk

### ISSUE THREAD

**Issue by guny74** [FreeTimeCoder82/node-red-contrib-pushsafer#1]
Hello,

thank you for the nice working "Node". But I have one question/problem.
I take pictures and have the information base64 encodes in my message and is want to set the value of the p, p1, p2 parameter "data:image/jpeg;base64,....."  directly without saving to disk.

Is there any way ?

Thanks you

Regards
  Thorsten

**Comment by FreeTimeCoder82** [comment]
Hi Thorsten,
unfortunately not.
Up to now you can use local files or an url from the web.
Then the base64 information will be generated inside the node.
The msg.payload input is always the notification message text.

I am currently working on an v2 of the node, with the Giphy parameter and also an read messages node, to check the state of notifications.
I will put your request on my ToDo list.

Regards,
Oliver

**Comment by guny74** [comment]
Hi Oliver,

thank you for the information and for taking it to the future feature list.

Regards
   Thorsten

**Comment by FreeTimeCoder82** [comment]
Hi Thorsten,
here a small sneak peak.
I added your request to the template of a notification.
![imagetemplate](https://user-images.githubusercontent.com/2456669/79698496-a2b32000-8289-11ea-83a8-b428e0b0b1f7.png)

Regards,
Oliver

**Comment by guny74** [comment]
Hello Oliver,

many thanks for implementing this.

So I could remove my workaround with Filewriting and deleting.

I wait for the update, so long my workaround is ok for me

Regards
  Thorsten

**Comment by guny74** [comment]
Hello Oliver,

short Question:  any new status about V2 ?

Thank you
  
regards Thorsten

**Comment by FreeTimeCoder82** [comment]
> Hello Oliver,
> 
> short Question: any new status about V2 ?
> 
> Thank you
> 
> regards Thorsten

Hello Thorsten,
I'm sorry, but due to Corona both private and professional projects have come to a standstill.
I will resume work as soon as possible and finish the v2 of the nodes within the next weeks. I promise ;-)
Best regards,
Oliver

**Comment by guny74** [comment]
> > Hello Oliver,
> > short Question: any new status about V2 ?
> > Thank you
> > regards Thorsten
> 
> Hello Thorsten,
> I'm sorry, but due to Corona both private and professional projects have come to a standstill.
> I will resume work as soon as possible and finish the v2 of the nodes within the next weeks. I promise ;-)
> Best regards,
> Oliver

Hello Oliver,

no hurry... 

Regards
   Thorsten

**Comment by Christchoper** [comment]
Hallo Oliver,
Ebenfalls von meiner Seite besten Dank zum tollen Node.
Gibt es allenfalls etwas neues zur V2?
Grüsse,
Chris

**Comment by FreeTimeCoder82** [comment]
> Hallo Oliver,
> Ebenfalls von meiner Seite besten Dank zum tollen Node.
> Gibt es allenfalls etwas neues zur V2?
> Grüsse,
> Chris

Hi Chris,
in the dev branch you can try the recent version if you like.
The only missing thing for the merge to main and a release is some documentation.
In the new release will be german and english support and I want to have a better Readme.md.
So, give me a few days and will be ready.
The nodes itself are ready to use, so try it from the dev branch.
Regards,
Oliver
